name: CI

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build iOS
        run: |
          xcodebuild \
            -project ios/ARDesignPro.xcodeproj \
            -scheme ARDesignPro \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            build

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build Android
        run: |
          cd android                # falls dein Android-Projekt direkt im Ordner android liegt
          chmod +x gradlew
          ./gradlew assembleDebug
