name: CI

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: swift package resolve
      - name: Run iOS Tests
        run: xcodebuild test -project ios/ARDesignPro.xcodeproj -scheme ARDesignPro -destination 'platform=iOS Simulator,name=iPhone 14'

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build Android
        run: cd android/ARDesignPro && ./gradlew assembleDebug
